version: '3.8'

services:
  mongodb:
    container_name: mongodb
    image: mongo
    volumes:
      - type: volume
        source: mongo_data
        target: /data/db
    networks:
      mongo:
        aliases:
          - mongo
        ipv4_address: 172.20.0.2

networks:
  mongo:
    ipam:
      driver: default
      config:
        - subnet: "172.20.0.1/24"

volumes:
  mongo_data:
